version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: influur_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: influur_demo
      POSTGRES_USER: influur
      POSTGRES_PASSWORD: influur
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
